// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VeloCity.Api.Models.Data;

#nullable disable

namespace VeloCity.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260602115220_AddActiveFlagToTrip")]
    partial class AddActiveFlagToTrip
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VeloCity.Api.Models.Line", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Lines");
                });

            modelBuilder.Entity("VeloCity.Api.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("AmountInBaseCurrency")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Currency")
                        .HasColumnType("integer");

                    b.Property<decimal>("ExchangeRate")
                        .HasColumnType("numeric");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TransactionId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Payments", t =>
                        {
                            t.HasCheckConstraint("CK_Payment_PaymentMethod", "\"PaymentMethod\" IN (1, 2, 3)");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 20.00m,
                            AmountInBaseCurrency = 20.00m,
                            CreatedAt = new DateTime(2026, 5, 20, 10, 0, 0, 0, DateTimeKind.Utc),
                            Currency = 1,
                            ExchangeRate = 1.00m,
                            PaymentMethod = 1,
                            Status = 1,
                            TransactionId = "TNX-20260520-A1B2C3D4",
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            Amount = 30.00m,
                            AmountInBaseCurrency = 30.00m,
                            CreatedAt = new DateTime(2026, 5, 21, 14, 30, 0, 0, DateTimeKind.Utc),
                            Currency = 1,
                            ExchangeRate = 1.00m,
                            PaymentMethod = 1,
                            Status = 1,
                            TransactionId = "TNX-20260521-E5F6G7H8",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("VeloCity.Api.Models.RouteStop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Direction")
                        .HasColumnType("integer");

                    b.Property<int>("LineId")
                        .HasColumnType("integer");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<int>("StopId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LineId");

                    b.HasIndex("StopId");

                    b.ToTable("RouteStops");
                });

            modelBuilder.Entity("VeloCity.Api.Models.Stop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ExternalId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ZoneId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.ToTable("Stops");
                });

            modelBuilder.Entity("VeloCity.Api.Models.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("EndStopId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsValidated")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("PurchasedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("StartStopId")
                        .HasColumnType("integer");

                    b.Property<int>("TicketTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ValidFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("VehicleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TicketTypeId");

                    b.HasIndex("UserId");

                    b.HasIndex("VehicleId");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsValidated = false,
                            Price = 4.00m,
                            PurchasedAt = new DateTime(2026, 5, 30, 15, 0, 0, 0, DateTimeKind.Utc),
                            TicketTypeId = 1,
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            IsValidated = true,
                            Price = 7.00m,
                            PurchasedAt = new DateTime(2026, 5, 31, 18, 0, 0, 0, DateTimeKind.Utc),
                            TicketTypeId = 13,
                            UserId = 2,
                            ValidFrom = new DateTime(2026, 5, 31, 18, 5, 0, 0, DateTimeKind.Utc),
                            ValidTo = new DateTime(2026, 5, 31, 19, 5, 0, 0, DateTimeKind.Utc),
                            VehicleId = 1
                        },
                        new
                        {
                            Id = 3,
                            IsValidated = true,
                            Price = 7.00m,
                            PurchasedAt = new DateTime(2026, 5, 25, 8, 0, 0, 0, DateTimeKind.Utc),
                            TicketTypeId = 13,
                            UserId = 2,
                            ValidFrom = new DateTime(2026, 5, 25, 8, 10, 0, 0, DateTimeKind.Utc),
                            ValidTo = new DateTime(2026, 5, 25, 9, 10, 0, 0, DateTimeKind.Utc),
                            VehicleId = 8
                        });
                });

            modelBuilder.Entity("VeloCity.Api.Models.TicketType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DurationInMinutes")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("ZoneLimit")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("TicketTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DurationInMinutes = 0,
                            IsActive = true,
                            Name = "Normalny - Miejski",
                            Price = 4.00m,
                            ZoneLimit = 0
                        },
                        new
                        {
                            Id = 2,
                            DurationInMinutes = 0,
                            IsActive = true,
                            Name = "Ustawowy Ulgowy - Miejski",
                            Price = 2.00m,
                            ZoneLimit = 0
                        },
                        new
                        {
                            Id = 3,
                            DurationInMinutes = 0,
                            IsActive = true,
                            Name = "Lokalny Ulgowy - Miejski",
                            Price = 2.35m,
                            ZoneLimit = 0
                        },
                        new
                        {
                            Id = 4,
                            DurationInMinutes = 0,
                            IsActive = true,
                            Name = "Normalny - Strefa 1",
                            Price = 4.80m,
                            ZoneLimit = 1
                        },
                        new
                        {
                            Id = 5,
                            DurationInMinutes = 0,
                            IsActive = true,
                            Name = "Ustawowy Ulgowy - Strefa 1",
                            Price = 2.40m,
                            ZoneLimit = 1
                        },
                        new
                        {
                            Id = 6,
                            DurationInMinutes = 0,
                            IsActive = true,
                            Name = "Lokalny Ulgowy - Strefa 1",
                            Price = 2.65m,
                            ZoneLimit = 1
                        },
                        new
                        {
                            Id = 7,
                            DurationInMinutes = 0,
                            IsActive = true,
                            Name = "Normalny - Strefa 2",
                            Price = 5.90m,
                            ZoneLimit = 2
                        },
                        new
                        {
                            Id = 8,
                            DurationInMinutes = 0,
                            IsActive = true,
                            Name = "Ustawowy Ulgowy - Strefa 2",
                            Price = 2.95m,
                            ZoneLimit = 2
                        },
                        new
                        {
                            Id = 9,
                            DurationInMinutes = 0,
                            IsActive = true,
                            Name = "Lokalny Ulgowy - Strefa 2",
                            Price = 3.10m,
                            ZoneLimit = 2
                        },
                        new
                        {
                            Id = 10,
                            DurationInMinutes = 0,
                            IsActive = true,
                            Name = "Gminny Normalny",
                            Price = 3.00m,
                            ZoneLimit = 1
                        },
                        new
                        {
                            Id = 11,
                            DurationInMinutes = 0,
                            IsActive = true,
                            Name = "Gminny Ustawowy Ulgowy",
                            Price = 1.50m,
                            ZoneLimit = 1
                        },
                        new
                        {
                            Id = 12,
                            DurationInMinutes = 0,
                            IsActive = true,
                            Name = "Gminny Lokalny Ulgowy",
                            Price = 1.80m,
                            ZoneLimit = 1
                        },
                        new
                        {
                            Id = 13,
                            DurationInMinutes = 60,
                            IsActive = true,
                            Name = "Przesiadkowy 60 min - Normalny",
                            Price = 7.00m,
                            ZoneLimit = 99
                        },
                        new
                        {
                            Id = 14,
                            DurationInMinutes = 60,
                            IsActive = true,
                            Name = "Przesiadkowy 60 min - Ustawowy Ulgowy",
                            Price = 3.50m,
                            ZoneLimit = 99
                        },
                        new
                        {
                            Id = 15,
                            DurationInMinutes = 60,
                            IsActive = true,
                            Name = "Przesiadkowy 60 min - Lokalny Ulgowy",
                            Price = 3.90m,
                            ZoneLimit = 99
                        },
                        new
                        {
                            Id = 16,
                            DurationInMinutes = 240,
                            IsActive = true,
                            Name = "Przesiadkowy 4h - Normalny",
                            Price = 12.60m,
                            ZoneLimit = 99
                        },
                        new
                        {
                            Id = 17,
                            DurationInMinutes = 240,
                            IsActive = true,
                            Name = "Przesiadkowy 4h - Ustawowy Ulgowy",
                            Price = 6.30m,
                            ZoneLimit = 99
                        },
                        new
                        {
                            Id = 18,
                            DurationInMinutes = 240,
                            IsActive = true,
                            Name = "Przesiadkowy 4h - Lokalny Ulgowy",
                            Price = 7.20m,
                            ZoneLimit = 99
                        });
                });

            modelBuilder.Entity("VeloCity.Api.Models.Timetable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<TimeSpan>("DepartureTime")
                        .HasColumnType("interval");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<int>("StopId")
                        .HasColumnType("integer");

                    b.Property<int>("TripId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StopId");

                    b.HasIndex("TripId");

                    b.ToTable("Timetables");
                });

            modelBuilder.Entity("VeloCity.Api.Models.Trip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("DriverId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("LineId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("LineId");

                    b.HasIndex("VehicleId");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("VeloCity.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Balance")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Balance = 0.00m,
                            Email = "driver@velocity.pl",
                            IsActive = true,
                            Name = "Piotr",
                            PasswordHash = "$2a$12$mVyskPgOLm8Ih5RumTF8xeXH1.B20XqSVu8SxcIOEV0F6EFmdNKMq",
                            Role = 2,
                            Surname = "Kierowca"
                        },
                        new
                        {
                            Id = 2,
                            Balance = 50.00m,
                            Email = "piboloz@student.wsb-nlu.edu.pl",
                            IsActive = true,
                            Name = "Piotr",
                            PasswordHash = "$2a$12$3s7iX0hZX00hn6JFwKJ06elVcg0A5mw9LVx4QHvaZW.Q3MWEyrPA2",
                            Role = 1,
                            Surname = "Bołoz"
                        },
                        new
                        {
                            Id = 3,
                            Balance = 0.00m,
                            Email = "dkflorek@student.wsb-nlu.edu.pl",
                            IsActive = true,
                            Name = "Dominik",
                            PasswordHash = "$2a$12$3s7iX0hZX00hn6JFwKJ06elVcg0A5mw9LVx4QHvaZW.Q3MWEyrPA2",
                            Role = 3,
                            Surname = "Florek"
                        });
                });

            modelBuilder.Entity("VeloCity.Api.Models.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SideNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SideNumber")
                        .IsUnique();

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Model = "Solaris Urbino 12",
                            SideNumber = "101"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Model = "Solaris Urbino 12",
                            SideNumber = "102"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Model = "Solaris Urbino 12",
                            SideNumber = "103"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Model = "Solaris Urbino 12",
                            SideNumber = "104"
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            Model = "Solaris Urbino 12",
                            SideNumber = "105"
                        },
                        new
                        {
                            Id = 6,
                            IsActive = true,
                            Model = "Solaris Urbino 18",
                            SideNumber = "201"
                        },
                        new
                        {
                            Id = 7,
                            IsActive = true,
                            Model = "Solaris Urbino 18",
                            SideNumber = "202"
                        },
                        new
                        {
                            Id = 8,
                            IsActive = true,
                            Model = "Mercedes-Benz Citaro",
                            SideNumber = "301"
                        },
                        new
                        {
                            Id = 9,
                            IsActive = true,
                            Model = "Mercedes-Benz Citaro",
                            SideNumber = "302"
                        },
                        new
                        {
                            Id = 10,
                            IsActive = true,
                            Model = "Mercedes-Benz Citaro",
                            SideNumber = "303"
                        },
                        new
                        {
                            Id = 11,
                            IsActive = true,
                            Model = "Autosan SanCity 9LE",
                            SideNumber = "401"
                        },
                        new
                        {
                            Id = 12,
                            IsActive = true,
                            Model = "Autosan SanCity 9LE",
                            SideNumber = "402"
                        },
                        new
                        {
                            Id = 13,
                            IsActive = true,
                            Model = "Autosan SanCity 12LF",
                            SideNumber = "403"
                        },
                        new
                        {
                            Id = 14,
                            IsActive = true,
                            Model = "MAN Lion's City",
                            SideNumber = "501"
                        },
                        new
                        {
                            Id = 15,
                            IsActive = true,
                            Model = "MAN Lion's City",
                            SideNumber = "502"
                        },
                        new
                        {
                            Id = 16,
                            IsActive = true,
                            Model = "Iveco Daily 70C",
                            SideNumber = "601"
                        },
                        new
                        {
                            Id = 17,
                            IsActive = true,
                            Model = "Iveco Daily 70C",
                            SideNumber = "602"
                        });
                });

            modelBuilder.Entity("VeloCity.Api.Models.Payment", b =>
                {
                    b.HasOne("VeloCity.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VeloCity.Api.Models.RouteStop", b =>
                {
                    b.HasOne("VeloCity.Api.Models.Line", "Line")
                        .WithMany("RouteStops")
                        .HasForeignKey("LineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VeloCity.Api.Models.Stop", "Stop")
                        .WithMany("RouteStops")
                        .HasForeignKey("StopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Line");

                    b.Navigation("Stop");
                });

            modelBuilder.Entity("VeloCity.Api.Models.Ticket", b =>
                {
                    b.HasOne("VeloCity.Api.Models.TicketType", "TicketType")
                        .WithMany()
                        .HasForeignKey("TicketTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VeloCity.Api.Models.User", "User")
                        .WithMany("Tickets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VeloCity.Api.Models.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId");

                    b.Navigation("TicketType");

                    b.Navigation("User");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("VeloCity.Api.Models.Timetable", b =>
                {
                    b.HasOne("VeloCity.Api.Models.Stop", "Stop")
                        .WithMany()
                        .HasForeignKey("StopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VeloCity.Api.Models.Trip", "Trip")
                        .WithMany("Timetables")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stop");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("VeloCity.Api.Models.Trip", b =>
                {
                    b.HasOne("VeloCity.Api.Models.User", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VeloCity.Api.Models.Line", "Line")
                        .WithMany("Trips")
                        .HasForeignKey("LineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VeloCity.Api.Models.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("Line");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("VeloCity.Api.Models.Line", b =>
                {
                    b.Navigation("RouteStops");

                    b.Navigation("Trips");
                });

            modelBuilder.Entity("VeloCity.Api.Models.Stop", b =>
                {
                    b.Navigation("RouteStops");
                });

            modelBuilder.Entity("VeloCity.Api.Models.Trip", b =>
                {
                    b.Navigation("Timetables");
                });

            modelBuilder.Entity("VeloCity.Api.Models.User", b =>
                {
                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
